# src/evolution_api.py
import httpx
import yaml
from loguru import logger

# Import the processing function from agent_logic
from .agent_logic import process_text_message

# Load configuration
try:
    with open("config/config.yaml", "r") as f:
        config = yaml.safe_load(f)
except FileNotFoundError:
    logger.error("Configuration file config/config.yaml not found for Evolution API setup.")
    config = {}
except yaml.YAMLError as e:
    logger.error(f"Error parsing configuration file for Evolution API setup: {e}")
    config = {}

EVOLUTION_CONFIG = config.get("evolution_api", {})
BASE_URL = EVOLUTION_CONFIG.get("base_url", "http://localhost:8080")
API_KEY = EVOLUTION_CONFIG.get("api_key", None)
INSTANCE_NAME = EVOLUTION_CONFIG.get("instance_name", "default")
WEBHOOK_VERIFY_TOKEN = EVOLUTION_CONFIG.get("webhook_verify_token", None)

HEADERS = {
    "apikey": API_KEY,
    "Content-Type": "application/json"
}

# Shared async HTTP client (created once, reused across requests)
_http_client: httpx.AsyncClient | None = None


async def get_http_client() -> httpx.AsyncClient:
    """Returns a shared async HTTP client instance."""
    global _http_client
    if _http_client is None or _http_client.is_closed:
        _http_client = httpx.AsyncClient(headers=HEADERS, timeout=10.0)
    return _http_client


async def close_http_client():
    """Closes the shared HTTP client. Call on application shutdown."""
    global _http_client
    if _http_client is not None and not _http_client.is_closed:
        await _http_client.aclose()
        _http_client = None
        logger.info("HTTP client closed.")


async def handle_evolution_webhook(payload: dict):
    """Processes incoming webhook messages from Evolution API."""
    logger.info(f"Handling webhook event: {payload.get('event')}")
    logger.debug(f"Full webhook payload: {payload}")

    # Check if it's a message event and if it's from a user (not group, not self)
    if payload.get("event") == "messages.upsert" and not payload.get("data", {}).get("key", {}).get("fromMe"):
        message_data = payload.get("data", {})
        key = message_data.get("key", {})
        message_info = message_data.get("message", {})
        sender_jid = key.get("remoteJid")

        if not sender_jid or "@g.us" in sender_jid: # Ignore group messages for now
            logger.info(f"Ignoring message from group or unknown sender: {sender_jid}")
            return

        logger.info(f"Received message from: {sender_jid}")

        # Determine message type (prioritize text for now)
        message_type = None
        text_content = None

        if "conversation" in message_info and message_info["conversation"]:
            message_type = "text"
            text_content = message_info["conversation"]
            logger.info(f"Message Type: {message_type}, Content: {text_content}")
        elif "extendedTextMessage" in message_info and message_info["extendedTextMessage"].get("text"):
            message_type = "text"
            text_content = message_info["extendedTextMessage"]["text"]
            logger.info(f"Message Type: extendedText, Content: {text_content}")
        elif "audioMessage" in message_info:
            message_type = "audio"
            logger.info("Message Type: audio (Handling not implemented yet)")
            # Placeholder: Add audio handling logic here (e.g., download, transcribe)
        elif "imageMessage" in message_info:
            message_type = "image"
            logger.info("Message Type: image (Handling not implemented yet)")
            # Placeholder: Add image handling logic here (e.g., download, OCR)
        else:
            logger.warning(f"Unsupported message type received: {list(message_info.keys())}")
            return

        # Process based on message type
        if message_type == "text" and text_content:
            try:
                # Call the agent logic processor
                response_text = await process_text_message(sender_jid, text_content)
                if response_text:
                    # Send the response back
                    await send_text_message(sender_jid, response_text)
                else:
                    logger.info("No response generated by agent logic.")
            except Exception as e:
                logger.error(f"Error processing text message: {e}")
                # Optionally send an error message back to the user
                await send_text_message(sender_jid, "Desculpe, ocorreu um erro ao processar sua mensagem.")
        # Add elif blocks here for audio/image processing later

    else:
        logger.info(f"Ignoring event type '{payload.get('event')}' or message from self.")

async def send_text_message(recipient_jid: str, message: str):
    """Sends a text message via the Evolution API using async httpx."""
    if not API_KEY:
        logger.error("Evolution API Key is not configured. Cannot send message.")
        return None # Return None to indicate failure
    if not BASE_URL:
        logger.error("Evolution API Base URL is not configured. Cannot send message.")
        return None

    endpoint = f"{BASE_URL}/message/sendText/{INSTANCE_NAME}"
    payload = {
        "number": recipient_jid,
        "options": {
            "delay": 1200,
            "presence": "composing"
        },
        "textMessage": {
            "text": message
        }
    }

    try:
        logger.info(f"Sending message to {recipient_jid}: {message}")
        client = await get_http_client()
        response = await client.post(endpoint, json=payload)
        response.raise_for_status()
        response_data = response.json()
        logger.debug(f"Evolution API response: {response_data}")
        logger.info(f"Message sent successfully to {recipient_jid}.")
        return response_data
    except httpx.TimeoutException:
        logger.error(f"Timeout sending message via Evolution API to {recipient_jid}")
        return None
    except httpx.HTTPStatusError as e:
        logger.error(f"HTTP error sending message via Evolution API: {e}")
        logger.error(f"Response status: {e.response.status_code}")
        logger.error(f"Response text: {e.response.text}")
        return None
    except httpx.RequestError as e:
        logger.error(f"Error sending message via Evolution API: {e}")
        return None

# Placeholder for other Evolution API interactions (e.g., sending media)
